force-app/main/default/objects/Account/fields/Chiffre_d_affaire__c.field-meta.xml
<CustomField>
    <fullName>Chiffre_d_affaire__c</fullName>
    <label>Chiffre affaire</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <defaultValue>0</defaultValue>
</CustomField>

force-app/main/default/objects/Order/fields/NetAmount__c.field-meta.xml
<CustomField>
    <fullName>NetAmount__c</fullName>
    <label>Net amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <defaultValue>0</defaultValue>
</CustomField>

force-app/main/default/classes/OrderTriggersTest.cls
@isTest
private class OrderTriggersTest {


    @isTest
    static void testAfterUpdateAccountCAWithTriggerBypass() {
        User user = TestDataFactory.createUser(true);
        System.runAs(user){
            Test.startTest();
            TestDataFactory.createAccountWithAnOrder('Test Account');
            Test.stopTest();
     
            List <Account> testAccounts = [SELECT Id, Chiffre_d_affaire__c FROM Account];

            for (Account acc : testAccounts) {
                System.assertEquals(0, acc.Chiffre_d_affaire__c);
            }
        }
    }

    @isTest
    static void testAfterUpdateAccountCAWithoutTriggerBypass() {
        User user = TestDataFactory.createUser(false);
        System.runAs(user){
            Test.startTest();
            TestDataFactory.createAccountWithAnOrder('Test Account');
            Test.stopTest();
     
            List <Account> testAccounts = [SELECT Id, Chiffre_d_affaire__c FROM Account];

            for (Account acc : testAccounts) {
                System.assertEquals(50, acc.Chiffre_d_affaire__c);
            }
        }
    }

    @isTest
    static void testBeforeUpdateNetAmountCalculation() {
                
        List <Order> testOrders = [SELECT Id, NetAmount__c FROM Order];

        for (Order ord : testOrders) {
            System.assertEquals(45, ord.NetAmount__c);
        }
    }
}